name: Validate Markdown

on:
  # Trigger the workflow on pull request
  pull_request_target:
    branches:
      - main
    paths:
      - "**.md"
      - "**.ipynb"

permissions:
  contents: read
  pull-requests: write

jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: Broken-Links-Crawler
    steps:
      - name: Checking links
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: "https://github.com/ScholliYT/Broken-Links-Crawler-Action"
          exclude_url_prefix: "https://github.com/"
          verbose: "true"
          max_retry_time: 30
          max_retries: 5
          max_depth: 1